local addon, ns = ...
local E, L, V, P, G = unpack(ElvUI)
P["thingsUI"] = P["thingsUI"] or {}
ns.Defaults = ns.Defaults or {}

P["thingsUI"].buffBars = {
    enabled             = false,
    frameStrata         = "MEDIUM",
    growthDirection     = "UP",
    width               = 240,
    height              = 25,
    spacing             = 1,
    statusBarTexture    = "ElvUI Blank",
    iconEnabled         = true,
    iconSpacing         = 1,
    iconZoom            = 0.1,
    inheritWidth        = true,
    inheritWidthOffset  = 0,
    stackAnchor         = "ICON",
    stackPoint          = "CENTER",
    stackXOffset        = 0,
    stackYOffset        = 0,
    backgroundColor     = { r = 0.1, g = 0.1, b = 0.1, a = 0.8 },
    useClassColor       = true,
    customColor         = { r = 0.2, g = 0.6, b = 1.0 },
    anchorEnabled       = true,
    anchorFrame         = "ElvUF_Player",
    anchorPoint         = "BOTTOM",
    anchorRelativePoint = "TOP",
    anchorXOffset       = 0,
    anchorYOffset       = 38,
}

ns.Defaults.BuffBarPresets = {
    dpsTank = {
        buffBars = {
            enabled             = true,
            growthDirection     = "UP",
            width               = 240,
            inheritWidth        = true,
            inheritWidthOffset  = 0,
            height              = 23,
            spacing             = 1,
            statusBarTexture    = "ElvUI Blank",
            useClassColor       = true,
            iconEnabled         = true,
            iconSpacing         = 1,
            iconZoom            = 0.1,
            stackAnchor         = "ICON",
            stackPoint          = "CENTER",
            stackXOffset        = 0,
            stackYOffset        = 0,
            anchorEnabled       = true,
            anchorFrame         = "ElvUF_Player",
            anchorPoint         = "BOTTOM",
            anchorRelativePoint = "TOP",
            anchorXOffset       = 0,
            anchorYOffset       = 50,
        },
        cdm = {
            nameFont            = "Expressway",
            nameFontSize        = 14,
            nameFontOutline     = "OUTLINE",
            namePosition        = "LEFT",
            namexOffset         = 2,
            nameyOffset         = 0,
            durationFont        = "Expressway",
            durationFontSize    = 14,
            durationFontOutline = "OUTLINE",
            durationPosition    = "RIGHT",
            durationxOffset     = -4,
            durationyOffset     = 0,
            countFont           = "Expressway",
            countFontSize       = 15,
            countFontOutline    = "OUTLINE",
            countPosition       = "CENTER",
            countxOffset        = 0,
            countyOffset        = 0,
        },
    },
    healer = {
        buffBars = {
            enabled             = true,
            growthDirection     = "DOWN",
            width               = 250,
            inheritWidth        = true,
            inheritWidthOffset  = 0,
            height              = 23,
            spacing             = 1,
            statusBarTexture    = "ElvUI Blank",
            useClassColor       = true,
            iconEnabled         = true,
            iconSpacing         = 1,
            iconZoom            = 0,
            stackAnchor         = "ICON",
            stackPoint          = "CENTER",
            stackXOffset        = 0,
            stackYOffset        = 0,
            anchorEnabled       = true,
            anchorFrame         = "ElvUF_Player_ClassBar",
            anchorPoint         = "TOP",
            anchorRelativePoint = "BOTTOM",
            anchorXOffset       = 0,
            anchorYOffset       = -2,
        },
        cdm = {
            nameFont            = "Expressway",
            nameFontSize        = 15,
            nameFontOutline     = "OUTLINE",
            namePosition        = "LEFT",
            namexOffset         = 4,
            nameyOffset         = 0,
            durationFont        = "Expressway",
            durationFontSize    = 15,
            durationFontOutline = "OUTLINE",
            durationPosition    = "RIGHT",
            durationxOffset     = -4,
            durationyOffset     = 0,
            countFont           = "Expressway",
            countFontSize       = 15,
            countFontOutline    = "OUTLINE",
            countPosition       = "CENTER",
            countxOffset        = 0,
            countyOffset        = 0,
        },
    },
}
