local addon, ns = ...
local E, L, V, P, G = unpack(ElvUI)
P["thingsUI"] = P["thingsUI"] or {}

P["thingsUI"].cdmIcons = {
    editModeLock = true,
    hideAuraBorder = false,
    essential = {
        spacing      = 1,
        overrideSize = true,
        lockAspect   = true,
        iconWidth    = 40,
        iconHeight   = 40,
        iconZoom     = 0.08,
        iconLockAspectRatio = true,
        growthDirection = "CENTERED_H",
        iconsPerRow     = 20,
        text = {
            showStacks      = true,
            stacksFont      = "Expressway",
            stacksFontSize  = 14,
            stacksFontOutline = "OUTLINE",
            stacksColor     = { r = 1, g = 1, b = 1 },
            stacksPoint     = "BOTTOMRIGHT",
            stacksXOffset   = -1,
            stacksYOffset   = 1,
            showCount       = true,
            countFont       = "Expressway",
            countFontSize   = 13,
            countFontOutline = "OUTLINE",
            countColor      = { r = 1, g = 1, b = 1 },
            countPoint      = "TOPLEFT",
            countXOffset    = 1,
            countYOffset    = -1,
            showCooldown    = true,
            cooldownFont    = "Expressway",
            cooldownFontSize = 16,
            cooldownFontOutline = "OUTLINE",
            cooldownColor   = { r = 1, g = 1, b = 1 },
            cooldownPoint   = "CENTER",
            cooldownXOffset = 0,
            cooldownYOffset = 0,
        },
    },
    utility = {
        spacing      = 1,
        overrideSize = true,
        lockAspect   = true,
        iconWidth    = 32,
        iconHeight   = 32,
        iconZoom     = 0.08,
        iconLockAspectRatio = true,
        growthDirection = "CENTERED_H",
        iconsPerRow     = 20,
        anchorEnabled       = true,
        anchorFrame         = "EssentialCooldownViewer",
        anchorPoint         = "TOP",
        anchorRelativePoint = "BOTTOM",
        anchorXOffset       = 0,
        anchorYOffset       = -2,
        text = {
            showStacks      = true,
            stacksFont      = "Expressway",
            stacksFontSize  = 12,
            stacksFontOutline = "OUTLINE",
            stacksColor     = { r = 1, g = 1, b = 1 },
            stacksPoint     = "BOTTOMRIGHT",
            stacksXOffset   = -1,
            stacksYOffset   = 1,
            showCount       = true,
            countFont       = "Expressway",
            countFontSize   = 11,
            countFontOutline = "OUTLINE",
            countColor      = { r = 1, g = 1, b = 1 },
            countPoint      = "TOPLEFT",
            countXOffset    = 1,
            countYOffset    = -1,
            showCooldown    = true,
            cooldownFont    = "Expressway",
            cooldownFontSize = 14,
            cooldownFontOutline = "OUTLINE",
            cooldownColor   = { r = 1, g = 1, b = 1 },
            cooldownPoint   = "CENTER",
            cooldownXOffset = 0,
            cooldownYOffset = 0,
        },
    },
    buffIcon = {
        spacing      = 1,
        overrideSize = true,
        lockAspect   = true,
        iconWidth    = 28,
        iconHeight   = 28,
        iconZoom     = 0.08,
        iconLockAspectRatio = true,
        growthDirection = "RIGHT",
        iconsPerRow     = 16,
        anchorEnabled       = true,
        anchorFrame         = "BARSETUP_TOP",
        anchorPoint         = "BOTTOM",
        anchorRelativePoint = "TOP",
        anchorXOffset       = 0,
        anchorYOffset       = 1,
        text = {
            showStacks      = true,
            stacksFont      = "Expressway",
            stacksFontSize  = 12,
            stacksFontOutline = "OUTLINE",
            stacksColor     = { r = 1, g = 1, b = 1 },
            stacksPoint     = "BOTTOMRIGHT",
            stacksXOffset   = -1,
            stacksYOffset   = 1,
            showCount       = true,
            countFont       = "Expressway",
            countFontSize   = 11,
            countFontOutline = "OUTLINE",
            countColor      = { r = 1, g = 1, b = 1 },
            countPoint      = "TOPLEFT",
            countXOffset    = 1,
            countYOffset    = -1,
            showCooldown    = true,
            cooldownFont    = "Expressway",
            cooldownFontSize = 14,
            cooldownFontOutline = "OUTLINE",
            cooldownColor   = { r = 1, g = 1, b = 1 },
            cooldownPoint   = "CENTER",
            cooldownXOffset = 0,
            cooldownYOffset = 0,
        },
    },
}
