local addon, ns = ...
local E, L, V, P, G = unpack(ElvUI)
P["thingsUI"] = P["thingsUI"] or {}
ns.Defaults = ns.Defaults or {}

P["thingsUI"].customGroups = {
    groups = {},
    nextID = 1,
}

function ns.Defaults.Group(id, name)
    return {
        id                   = id,
        name                 = name or ("Group " .. id),
        enabled              = false,
        iconSize             = 36,
        iconWidth            = 36,
        iconHeight           = 36,
        squareIcon           = true,
        spacing              = 3,
        growth               = "RIGHT",
        columns              = 0,
        wrapDir              = "DOWN",
        hideZeroCharges      = false,
        qualityBorder        = true,
        qualityScale         = 0.42,
        qualityPoint         = "TOPLEFT",
        qualityXOffset       = 0,
        qualityYOffset       = 0,
        qualityLayer         = "TOP",
        fleetingMarker       = true,
        fleetingBorderSize   = 2,
        fleetingBorderInset  = 0,
        fleetingBorderColor  = { r = 0.2, g = 0.8, b = 1, a = 1 },
        fleetingBorderStroke = true,
        showBorder           = false,
        borderSize           = 1,
        borderInset          = 0,
        borderColor          = { r = 0, g = 0, b = 0, a = 1 },
        borderStroke         = false,
        scopeOrder           = { "global", "class", "spec" },
        anchorFrame          = "UIParent",
        anchorFrameCustom    = "",
        anchorPoint          = "CENTER",
        anchorRelativePoint  = "CENTER",
        anchorXOffset        = 0,
        anchorYOffset        = 0,
        text = {
            showCooldown        = true,
            cooldownFont        = "Expressway",
            cooldownFontSize    = 16,
            cooldownFontOutline = "OUTLINE",
            cooldownColor       = { r = 1, g = 1, b = 1 },
            cooldownPoint       = "CENTER",
            cooldownXOffset     = 0,
            cooldownYOffset     = 0,
            showCount           = true,
            countFont           = "Expressway",
            countFontSize       = 12,
            countFontOutline    = "OUTLINE",
            countColor          = { r = 1, g = 1, b = 1 },
            countPoint          = "BOTTOMRIGHT",
            countXOffset        = -1,
            countYOffset        = 1,
            showStacks          = true,
            stacksFont          = "Expressway",
            stacksFontSize      = 9,
            stacksFontOutline   = "OUTLINE",
            stacksColor         = { r = 2, g = 255, b = 0 },
            stacksPoint         = "TOP",
            stacksXOffset       = 0,
            stacksYOffset       = 5,
        },
        global  = { spells = {}, items = {} },
        classes = {},
        specs   = {},
    }
end
