local addon, ns = ...
local E, L, V, P, G = unpack(ElvUI)
P["thingsUI"] = P["thingsUI"] or {}

P["thingsUI"].damageMeter = {
    provider = "DETAILS",
    tui = {
        windows = {},
        layout = "2",
        splitH = 0.5,
        splitV = 0.5,
        barHeight = 23.4,
        barSpacing = -1,
        autoFit = true,
        barBgAlpha = 0,
        bgAlpha = 0,
        windowBorder = false,
        windowBorderSize = 1,
        windowBorderColor = { r = 0, g = 0, b = 0, a = 1 },
        windowDivider = true,
        headerBorder = true,
        panelInset = 0,
        contentPad = -1,
        headerHeight = 25,
        headerFontSize = 13,
        font = "Expressway",
        fontSize = 12,
        valueFontSize = 12,
        fontOutline = "OUTLINE",
        fontShadow = false,
        barTexture = "ElvUI Blank",
        barBorder = true,
        classColor = true,
        barColor = { r = 0.35, g = 0.55, b = 0.8 },
        iconStyle = "spec",
        iconZoom = 0.05,
        iconGap = -1,
        iconBorder = true,
        iconBorderSize = 1,
        iconBorderColor = { r = 0, g = 0, b = 0, a = 1 },
        showRank = false,
        numberFormat = "both",
        refreshRate = 5,
        windowGap = -1,
        windowWidth = 260,
        windowHeight = 180,
    },
}
