local addon, ns = ...
local E, L, V, P, G = unpack(ElvUI)
P["thingsUI"] = P["thingsUI"] or {}
ns.Defaults = ns.Defaults or {}

P["thingsUI"].specialBars = {
    specs = {},
}

ns.SPECIAL_BAR_DEFAULTS = {
    enabled             = false,
    spellID             = nil,
    spellName           = "",
    width               = 230,
    inheritWidth        = false,
    inheritWidthOffset  = 0,
    height              = 24,
    inheritHeight       = false,
    inheritHeightOffset = 0,
    statusBarTexture    = "ElvUI Blank",
    font                = "Expressway",
    fontSize            = 14,
    fontOutline         = "OUTLINE",
    useClassColor       = true,
    customColor         = { r = 0.2, g = 0.6, b = 1.0 },
    backgroundColor     = { r = 0.1, g = 0.1, b = 0.1, a = 0.6 },
    showBackdrop        = false,
    backdropColor       = { r = 0.1, g = 0.1, b = 0.1, a = 0.6 },
    iconEnabled         = true,
    iconSpacing         = 1,
    iconZoom            = 0.1,
    showStacks          = true,
    stackFontSize       = 14,
    stackFontOutline    = "OUTLINE",
    stackPoint          = "CENTER",
    stackAnchor         = "ICON",
    stackXOffset        = 0,
    stackYOffset        = 0,
    showName            = true,
    namePoint           = "LEFT",
    nameXOffset         = 2,
    nameYOffset         = 0,
    showDuration        = true,
    durationPoint       = "RIGHT",
    durationXOffset     = -4,
    durationYOffset     = 0,
    anchorMode          = "UIParent",
    anchorFrame         = "UIParent",
    anchorPoint         = "CENTER",
    anchorRelativePoint = "CENTER",
    anchorXOffset       = 0,
    anchorYOffset       = 0,
    frameStrata         = "MEDIUM",
}

ns.SPECIAL_ICON_DEFAULTS = {
    enabled               = false,
    spellID               = nil,
    spellName             = "",
    width                 = 36,
    height                = 36,
    keepAspectRatio       = true,
    zoom                  = 0.1,
    anchorMode            = "UIParent",
    anchorFrame           = "UIParent",
    anchorPoint           = "CENTER",
    anchorRelativePoint   = "CENTER",
    anchorXOffset         = 0,
    anchorYOffset         = 0,
    showCooldown          = true,
    desaturateWhenInactive = false,
    showBorder            = false,
    borderSize            = 1,
    borderColor           = { r = 0, g = 0, b = 0, a = 1 },
    borderInset           = 0,
    borderStroke          = false,
    showStacks            = true,
    stackFont             = "Expressway",
    stackFontSize         = 14,
    stackFontOutline      = "OUTLINE",
    stackColor            = { r = 1, g = 1, b = 1 },
    stackPoint            = "BOTTOMRIGHT",
    stackXOffset          = 0,
    stackYOffset          = 0,
    showDuration          = true,
    durationFont          = "Expressway",
    durationFontSize      = 14,
    durationFontOutline   = "OUTLINE",
    durationColor         = { r = 1, g = 1, b = 1 },
    durationPoint         = "CENTER",
    durationXOffset       = 0,
    durationYOffset       = 0,
    showGlow              = false,
    glowType              = "pixel",
    glowColor             = { r = 1, g = 1, b = 0, a = 1 },
    glowN                 = 8,
    glowFrequency         = 0.25,
    glowLength            = 10,
    glowThickness         = 2,
    glowXOffset           = 0,
    glowYOffset           = 0,
    glowInsideBorder      = false,
    overrideGroupText     = false,
    frameStrata           = "MEDIUM",
}

-- Also exposed under the unified ns.Defaults namespace.
ns.Defaults.SpecialBar  = ns.SPECIAL_BAR_DEFAULTS
ns.Defaults.SpecialIcon = ns.SPECIAL_ICON_DEFAULTS
